sudo: required
  

language: python
python:
    - 2.7

before_install:
   - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install:
   - pip install -r requirements.txt

script: 
 - mkdir cctbx
 - cd cctbx
 - python install_cctbx.py
