sudo: required
  
language: python
python:
    - 2.7
cache:  
   -pip
   directories:
     - .autoconf
     - $HOME/.m2
     -build
     -modules
     -base
    

before_install:
   - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

#install:
#   - pip install -r requirements.txt

script: 
 - curl https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py > bootstrap.py
 - python bootstrap.py #--builder=qrefine
 - source build/setpaths.sh
 - iotbx.python -m  pip install -U pip
 - iotbx.python -m  pip install -r requirements.txt
