sudo: required
  
language: python
python:
    - 2.7
cache:  
   directories:
     - .autoconf
     - $HOME/.m2
     - /home/travis/build/qrefine/qrefine/build
     - /home/travis/build/qrefine/qrefine/modules
     - /home/travis/build/qrefine/qrefine/base
    
#before_install:
   #- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

#install:
#   - pip install -r requirements.txt

script: 
 #- curl https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py > bootstrap.py
 #- travis_wait 60 python bootstrap.py --builder=qrefine  --nproc=6 base # hot update build
 - curl http://cci.lbl.gov/~bkpoon/base_1.11.1-2575.tar.xz
 - xz -d base_1.11.1-2575.tar.xz
 - tar -xvf base_1.11.1-2575.tar
 - ls -ltr 
 - pwd
 - source build/setpaths.sh
 - iotbx.python -m  pip install -U pip
 - iotbx.python -m  pip install -r requirements.txt
