sudo: required
  

language: python
python:
    - 2.6
    - 2.7

before_install:
   - sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran

install:
   - pip install -r requirements.txt

script: python setup.py
