os:
  - osx

python:
- '2.7'
cache:  
   directories:
     - /Users/travis/build/qrefine/qrefine/build
     - /Users/travis/build/qrefine/qrefine/modules
     - /Users/travis/build/qrefine/qrefine/base
    
#before_install:
   #- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran gtk2.0

#install:
#   - pip install -r requirements.txt

script: 
 #- curl https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py > bootstrap.py
 #- curl http://cci.lbl.gov/~bkpoon/base_1.11.1-2575.tar.xz >  base_1.11.1-2575.tar.xz
 #- xz -d base_1.11.1-2575.tar.xz
 #- tar -xvf base_1.11.1-2575.tar
 #- travis_wait 45 python bootstrap.py --builder=cctbx
 - source build/setpaths.sh
 - phenix.fetch_pdb 2hr0
 - cd modules 
 - git clone  https://github.com/qrefine/qrefine.git
 - cd qrefine
 - git clone https://github.com/qrefine/qr-core.git
 - mv qr-core core
 - cctbx.python -m pip install -r requirements.txt
 - cctbx.python -m pip install -r core/requirements.txt
 - libtbx.configure qrefine
 #- qr.test
 #- source build/setpaths.sh
 #- cctbx.python -m  pip install -U pip
 #- cctbx.python -m  pip install -r modules/qrefine/requirements.txt
 #- cctbx.python modules/qrefine/core/qr.py
 - rm -rf /Users/travis/build/qrefine/qrefine/modules/qrefine
